name: lint batch
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get update -y && sudo apt-get install -y libvips
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - run: bundle exec apertiiif lint
